name: deploy.yml
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.NDENO_DEV_ROLE }}
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        env:
          NDENO_DEV_BUCKET: ${{ secrets.NDENO_DEV_BUCKET }}
        run: |
          ls 
        # run: |
        #   ls 
        #   aws s3 sync dist/ $NDENO_DEV_BUCKET